/**
 * In-app Strong's lexicon loader
 *
 * Data: public/strongs-greek.json  (5 523 entries, ~0.62 MB)
 *       public/strongs-hebrew.json (8 674 entries, ~1.11 MB)
 *
 * Generated by:  node scripts/processStrongs.mjs
 * Source:        github.com/openscriptures/strongs  (public domain)
 *
 * Entry shape: { l, x, p, d }
 *   l = lemma (original script)
 *   x = transliteration
 *   p = pronunciation guide
 *   d = definition (strongs_def — KJV usage)
 */

/* ── In-memory cache ─────────────────────────────────────────────────── */
const _data     = { greek: null, hebrew: null }
const _promises = { greek: null, hebrew: null }

/**
 * Lazy-loads and caches the Strong's dictionary for `lang`.
 * @param {'greek'|'hebrew'} lang
 * @returns {Promise<Object>} key → { l, x, p, d }
 */
export async function loadStrongs(lang) {
  if (_data[lang])     return _data[lang]
  if (_promises[lang]) return _promises[lang]

  _promises[lang] = fetch(`/strongs-${lang}.json`)
    .then(r => {
      if (!r.ok) throw new Error(
        `Strong's ${lang} data not found (HTTP ${r.status}). ` +
        `Run: npm run process:strongs`
      )
      return r.json()
    })
    .then(data => {
      _data[lang]     = data
      _promises[lang] = null
      return data
    })
    .catch(err => {
      _promises[lang] = null
      throw err
    })

  return _promises[lang]
}

/**
 * Synchronous lookup — only works after loadStrongs() has resolved.
 * @param {'greek'|'hebrew'} lang
 * @param {string} strongsId  e.g. "G1161", "H7225G"
 * @returns {{ l, x, p, d }|null}
 */
export function lookupStrongs(lang, strongsId) {
  const data = _data[lang]
  if (!data || !strongsId) return null
  // Strip prefix letter and any trailing disambiguator letters (e.g. "G" in "H7225G")
  const raw = strongsId.replace(/^[GHgh]/, '').replace(/[A-Za-z]+$/, '')
  const num = parseInt(raw, 10)
  if (isNaN(num)) return null
  return data[String(num)] || null
}

/**
 * Determine language from a Strong's ID.
 * @param {string} id
 * @returns {'greek'|'hebrew'|null}
 */
export function strongsLang(id) {
  if (!id) return null
  const c = id[0].toUpperCase()
  if (c === 'G') return 'greek'
  if (c === 'H') return 'hebrew'
  return null
}

/**
 * Extract just the numeric portion of a Strong's ID.
 * @param {string} id e.g. "G1161" → 1161
 */
export function strongsNum(id) {
  if (!id) return null
  const raw = id.replace(/^[GHgh]/, '').replace(/[A-Za-z]+$/, '')
  const n   = parseInt(raw, 10)
  return isNaN(n) ? null : n
}

/**
 * Return the cached data object (or null if not loaded).
 */
export function getCachedStrongs(lang) {
  return _data[lang]
}
